package carloschau.tokengenerator.security

import org.springframework.security.web.authentication.preauth.PreAuthenticatedGrantedAuthoritiesUserDetailsService

class PreAuthenticatedUserDetailsService : PreAuthenticatedGrantedAuthoritiesUserDetailsService() {

}