apiVersion: v1
kind: Service
metadata:
  name: token-generator-service
spec:
  type: LoadBalancer
  selector:
    app: token-generator
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8080