# This is a basic workflow to help you get started with Actions

name: Build & Push Docker Image

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:  
  push-image:
    runs-on: ubuntu-20.04
    env:
      CONTAINER_REPO_USERNAME: ${{ secrets.CONTAINER_REPO_USERNAME }}
      CONTAINER_REPO_PASSWORD: ${{ secrets.CONTAINER_REPO_PASSWORD }}
    steps:
      - uses: actions/checkout@v2

      - name: Login docker hub
        uses: docker/login-action@v1
          with:
            username: ${{ secrets.CONTAINER_REPO_USERNAME }}
            password: ${{ secrets.CONTAINER_REPO_PASSWORD }}

      - name: Build and push image
        run: |
          chmod +x ./gradlew
          ./gradlew dockerPushImage -PdockerImageTag=latest
