# This is a basic workflow to help you get started with Actions

name: Docker Image Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, github-action-debug ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:  
  push-image:
    runs-on: ubuntu-20.04
    env:
      CONTAINER_REPO_USERNAME: ${{ secrets.CONTAINER_REPO_USERNAME }}
      CONTAINER_REPO_PASSWORD: ${{ secrets.CONTAINER_REPO_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - name: grant execute permission to gradlew
        run: chmod +x ./gradlew
      - name: push image to repo
        run: ./gradlew dockerPushImage
      # Set the target AKS cluster.
      - uses: Azure/aks-set-context@v1
      with:
       creds: '${{ secrets.AZURE_CREDENTIALS }}'
       cluster-name: contoso
       resource-group: contoso-rg

      - uses: Azure/k8s-create-secret@v1
       with:
         container-registry-url: contoso.azurecr.io
         container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
         container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
         secret-name: demo-k8s-secret

      - uses: Azure/k8s-deploy@v1
       with:
         manifests: |
           manifests/deployment.yml
           manifests/service.yml
         images: |
           demo.azurecr.io/k8sdemo:${{ github.sha }}
         imagepullsecrets: |
           demo-k8s-secret
       
